name = "scholarly-website"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
NUXT_PUBLIC_API_BASE_URL = "https://directus-production-a710.up.railway.app"

# Workers KV namespace for caching (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your_kv_namespace_id"

# D1 database for data storage (optional)
# [[d1_databases]]
# binding = "DB"
# database_name = "scholarly_db"
# database_id = "your_d1_database_id"

# API routes as Workers functions
[[routes]]
pattern = "/api/getResponse"
zone_name = "scholarlyconsulting.co"

[[routes]]
pattern = "/api/saveChatbotMessages"
zone_name = "scholarlyconsulting.co"

# Static asset routes
[[routes]]
pattern = "/_nuxt/*"
zone_name = "scholarlyconsulting.co"

[[routes]]
pattern = "/_ipx/*"
zone_name = "scholarlyconsulting.co"

# Catch-all for SPA routing
[[routes]]
pattern = "/*"
zone_name = "scholarlyconsulting.co"